class AppAssets {
  static const String baseURL = "assets/images/";
  static const String logo = "${baseURL}Group 5.png";
  static const String blueLogo = "${baseURL}Group5.png";
  static const String banner1 = "${baseURL}Property 1=Default (1).png";
  static const String banner2 = "${baseURL}Property 1=Variant2.png";
  static const String banner3 = "${baseURL}Property 1=Variant3.png";
  static const String WomensFashion = "${baseURL}Ellipse 14.png";
  static const String MenFashion = "${baseURL}Ellipse 15.png";
  static const String Laptops = "${baseURL}Ellipse 16.png";
  static const String Baby = "${baseURL}Ellipse 17.png";
  static const String Beauty = "${baseURL}Ellipse 14 (1).png";
  static const String Headphones = "${baseURL}Ellipse 15 (1).png";
  static const String SkinCare = "${baseURL}Ellipse 16 (1).png";
  static const String Camera = "${baseURL}Ellipse 17 (1).png";
  static const String product1 = "${baseURL}Frame 9 (1).png";
  static const String product2 = "${baseURL}Frame 11.png";
  static const String product3 = "${baseURL}Frame 10.png";
  static const String footWearImage = "${baseURL}Frame 17.png";
  static const String category1 = "${baseURL}Frame 32.png";
  static const String category2 = "${baseURL}Frame 31.png";
  static const String categoryBannerImage2 = "${baseURL}Frame 49.png";
  static const String productImage1 = "${baseURL}Property 1=Default (2).png";
  static const String productImage2 = "${baseURL}Property 1=Variant2 (1).png";
  static const String productImage3 = "${baseURL}Property 1=Variant3 (1).png";
  static const String removeIcon = "${baseURL}delete 1.png";
  static const String tshirtImage = "${baseURL}Frame 47.png";
  static const String shortsImage = "${baseURL}Frame 48.png";
  static const String jeansImage = "${baseURL}Frame 49.png";
  static const String pantsImage = "${baseURL}Frame 50.png";
  static const String footWear = "${baseURL}Frame 54.png";
  static const String suitsImage = "${baseURL}Frame 55.png";
  static const String watchesImage = "${baseURL}Frame 51.png";
  static const String bagsImage = "${baseURL}Frame 52.png";
  static const String eyewearImage = "${baseURL}Frame 53.png";
  static const String dressesImage = "${baseURL}Frame 38.png";
  static const String womenJeansImage = "${baseURL}Frame 39.png";
  static const String skirtsImage = "${baseURL}Frame 40.png";
  static const String pajamasImage = "${baseURL}Frame 41.png";
  static const String womenBagsImage = "${baseURL}Frame 42.png";
  static const String womenTshirtImage = "${baseURL}Frame 43.png";
  static const String womenFootwearImage = "${baseURL}Frame 44.png";
  static const String womenEyewearImage = "${baseURL}Frame 45.png";
  static const String womenWatchesImage = "${baseURL}Frame 46.png";
  static const String footWearcart = "${baseURL}Frame 64.png";
  static const String footWearfav = "${baseURL}Frame 65.png";
  static const String footWearfav2 = "${baseURL}Frame 65 (1).png";
  static const String footWearfav3 = "${baseURL}Frame 65 (2).png";
  static const String footWear1 = "${baseURL}Frame 68.png";
  static const String footWear2 = "${baseURL}Frame 68 (1).png";
  static const String footWear3 = "${baseURL}Frame 68 (2).png";
  static const String footWear4 = "${baseURL}Frame 68 (3).png";
  static const String footWear5 = "${baseURL}Frame 68 (4).png";
  static const String footWear6 = "${baseURL}Frame 68 (5).png";
}
